### ISSUE TITLE
Generating Abnormal PDB results

### ISSUE THREAD

**Issue by Aolibaba** [bjing2016/alphaflow#18]
Thanks for open source this amazing work AlphaFlow. 
After I deployed this project to my computer, I found that the generated PDB results seems abnormal, whether using AlphaFLow or ESMFlow. 
Has anyone else met this problem?
![P41440_3](https://github.com/bjing2016/alphaflow/assets/32875000/0abfcc07-9ded-419c-bc4e-94a523752fd2)
![Q15758_1](https://github.com/bjing2016/alphaflow/assets/32875000/44c07b69-b62e-4148-92ba-3003253ce3a1)

**Comment by eunos-1128** [comment]
I guess you just have generated the models with multiple states(one PDB file having models more than one)

If you use PyMOL, you can split them into each PyMOL object using `split_states {obj_name}`.

**Comment by Aolibaba** [comment]
eunos-1128, thank you very much! this actually solved my problem.
