### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'opm_first' and 'fuse_projection_weights'

### ISSUE THREAD

**Issue by BLEACH366** [bjing2016/alphaflow#2]
Hello,I put weights, csv and a3m in folders (Especially, a3m in /cluster/home/xxx/alphaflow/splits/6DS0_A/a3m/6DS0_A.a3m), and run following code:

`python predict.py --mode alphafold --input_csv /cluster/home/xxx/alphaflow/splits/6DS0_test.csv --msa_dir /cluster/home/xxx/alphaflow/splits --weights /cluster/home/xxx/alphaflow/splits/alphaflow_pdb_base_202402.pt --samples 200 --outpdb /cluster/home/xxx/alphaflow/splits/output --self_cond --resample`

then I meet the error:

```
2024-02-22 13:45:48,506 [node83:61063] [INFO] Loading the model
Traceback (most recent call last):
  File "/cluster/home/xxx/alphaflow/predict.py", line 132, in <module>
    main()
  File "/cluster/home/xxx/.conda/envs/alphaflow/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/cluster/home/xxx/alphaflow/predict.py", line 78, in main
    model = model_class(**ckpt['hyper_parameters'], training=False)
  File "/cluster/home/xxx/alphaflow/alphaflow/model/wrapper.py", line 496, in __init__
    self.model = AlphaFold(config,
  File "/cluster/home/xxx/alphaflow/alphaflow/model/alphafold.py", line 73, in __init__
    self.extra_msa_stack = ExtraMSAStack(
TypeError: __init__() missing 2 required positional arguments: 'opm_first' and 'fuse_projection_weights'
```

Could you offer me some help to solve it? Thanks.

**Comment by bjing2016** [comment]
This looks like an OpenFold version mismatch --- did you install OpenFold with the command provided in the README, or some other way?

**Comment by BLEACH366** [comment]
Yes, I did it as in the README:

`pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@5484c38'`

and get openfold 2.0.0, is this version right?

**Comment by bjing2016** [comment]
Ah, the commit is wrong; it should be 
`pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@103d037'` 
The README has been updated.

**Comment by BLEACH366** [comment]
Ok, I change the openfold version and it works. Thanks

**Comment by aishwaryshivgan** [comment]
Hello all, I am getting following error with `pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@103d037`

`     /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/c10/util/C++17.h:24:2: error: #error You need C++17 to compile PyTorch
         24 | #error You need C++17 to compile PyTorch
            |  ^~~~~
      In file included from /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                       from /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                       from /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                       from /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:4,
                       from /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                       from /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                       from /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:9,
                       from /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/torch/extension.h:5,
                       from openfold/utils/kernel/csrc/softmax_cuda_kernel.cu:18:
      /home/aishwaryts/.conda/envs/ALPHAFLOW/lib/python3.9/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
          4 | #error C++17 or later compatible compiler is required to use ATen.
            |  ^~~~~
      error: command '/home/aishwaryts/.conda/envs/ALPHAFLOW/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for openfold
  Running setup.py clean for openfold
Failed to build openfold
ERROR: Failed to build installable wheels for some pyproject.toml based projects (openfold)
`

Any idea how to fix it?
