### ISSUE TITLE
Availability of MD Ensemble Evaluation Scripts

### ISSUE THREAD

**Issue by v-shaoningli** [bjing2016/alphaflow#22]
Hi all! Thanks for your work.

I'm reaching out to inquire about the availability of MD ensemble evaluation scripts, particularly for metrics beyond RMSD and RMSF. While these two metrics are relatively straightforward to generate, I've found challenges reproducing others like Root Mean W2-Dist and PCAs.
Could u provide guidance or scripts to assist with calculating these metrics? Really thanks for your help.

Best,
Shaoning

**Comment by bjing2016** [comment]
These scripts will be uploaded soon; thanks for your patience!

**Comment by bjing2016** [comment]
The evaluation scripts have now been uploaded; thanks for your patience!
