### ISSUE TITLE
when traing alphaflow from scratch, show AttributeError: 'AlphaFoldWrapper' object has no attribute 'extra_msa_stack'

### ISSUE THREAD

**Issue by Paulie-ai** [bjing2016/alphaflow#26]
Hi BoWen, i am using alphaflow train.py to trying run, but find error with below:
    AttributeError: 'AlphaFoldWrapper' object has no attribute 'extra_msa_stack
    and i am using:
    python train.py --lr 5e-4 --noise_prob 0.8 --accumulate_grad 8 --train_epoch_len 80000 --train_cutoff 2018-05-01 --filter_chains  --train_data_dir ../unpack_mmcif_out --train_msa_dir ../openfold/pdb --mmcif_dir ../pdb_mmcif --val_msa_dir ../openfold/alignment_db --run_name alphaflow_train
    Is need add extra_msa_stack in AlphaFoldWrapper class or drop this line?

**Comment by Paulie-ai** [comment]
directly is from openfold/utils/import_weights.py", line 325, in generate_translation_dict
    ems_blocks = model.extra_msa_stack.blocks

**Comment by Paulie-ai** [comment]
https://github.com/bjing2016/alphaflow/blob/master/train.py#L142
should change mode.esmfold to model.model. this fixed  above error

**Comment by bjing2016** [comment]
Thanks! This has been fixed.
