### ISSUE TITLE
Is biopandas needed?

### ISSUE THREAD

**Issue by johnny-rodriguez** [bjing2016/alphaflow#32]
When I try to run python predict.py --mode esmfold --input_csv /data/AI_tools/alphaflow/test/GPRC_B.csv --weights /data/AI_tools/alphaflow/weights/esmflow_md_base_202402.pt --samples 10 --outpdb /data/AI_tools/alphaflow/test/output.
I get an error saying biopandas is not found. However, I see that the docker file and the conda environment do not specify that biopandas needs to be installed.

**Comment by bjing2016** [comment]
No, biopandas is not needed. This was an issue with the most recent PR. I have reverted the PR --- could you pull the latest commit and try again?
