### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'no_column_attention'

### ISSUE THREAD

**Issue by Bloeci** [bjing2016/alphaflow#5]
Hi,
I've been trying to do some experiments using your model and scripts and running into a problem. The error arises when using the following command from a testing directory in the main project location:
```shell
python3 ../predict.py \
    --weights ../model_weights/alphaflow_pdb_distilled_202402.pt \
    --mode alphafold \
    --input_csv ghsr.csv \
    --msa_dir ./msas \
    --samples 10 \
    --outpdb ./out \
    --noisy_first \
    --no_diffusion
```

I get the error:
```shell
2024-02-27 08:10:02,292 [iwe547170:52263] [INFO] Loading the model
Traceback (most recent call last):
  File "/media/data/software/alphaflow/workdir/../predict.py", line 138, in <module>
    main()
  File "/home/iwe34/anaconda3/envs/alphaflow/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/data/software/alphaflow/workdir/../predict.py", line 84, in main
    model = model_class(**ckpt['hyper_parameters'], training=False)
  File "/media/data/software/alphaflow/alphaflow/model/wrapper.py", line 496, in __init__
    self.model = AlphaFold(config,
  File "/media/data/software/alphaflow/alphaflow/model/alphafold.py", line 77, in __init__
    self.evoformer = EvoformerStack(
TypeError: __init__() missing 1 required positional argument: 'no_column_attention'
```

To figure out why that happened, I modified the `alphaflow/config.py` file by manually adding the flag `no_column_attention: False` and realized later, that this config is only used when the `predict.py` script is called with the additional flag `--original_weights=True`. 

However, inspecting the loaded config `ckpt` from the lines
```python
if args.weights:
    ckpt = torch.load(args.weights, map_location='cpu')
    model = model_class(**ckpt['hyper_parameters'], training=False)
```
showed that the model weights `alphaflow_pdb_distilled_202402.pt` doesn't contain the `no_column_attention` field. It worked fine when I used the original weights `params_model_1.npz` (apart from getting a CUDA error, another problem).

**Simple question**: What am I doing wrong? Why can I provide new model weights when these could never be used because the `EvoformerStack` in `openfold` requires this argument?

**Comment by bjing2016** [comment]
Hm, I'm not sure why adding the line `--original_weights=True` worked. However, if there is an error about `no_column_attention`, then the OpenFold version is probably wrong. Did you install OpenFold using the pip command in the README or some other way?

**Comment by Bloeci** [comment]
Hi,
thanks for the quick reply. To clarify something, adding the flag `no_column_attention: False` to the `config.py` doesn't work. I experimented to see if this would solve the problem. After that, I realized that this config is never read by the `model_class` (the code snipped in my first post, third box), because it loads the hyperparameter from the `alphaflow_pdb_distilled_202402.pt`. And these weights don't contain the flag `no_column_attention`.

However, for some reason, I can't trace it back. The version I installed was not the correct one, and looking at the correct openfold version from the commit hash `103d037`, the attribute `no_column_attention` is missing in the `EvoformerStack` class. In older/newer versions this flag exists.

When repeating the installation instructions again, I ran into some issues regarding pytorch-cuda support because, for some reason (I'm definitely not an expert), the instructions don't work on my machine (I use an NVIDIA GeForce RTX 3070, CUDA 11.4). I ran into error when trying to install `openfold`. The main error has something to do with the `nvcc`, because I get (I have cropped the output, complete message attached)
```bash
(alphaflow) Ξ software/alphaflow git:(master) ▶ pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@103d037'
Collecting openfold@ git+https://github.com/aqlaboratory/openfold.git@103d037
  Cloning https://github.com/aqlaboratory/openfold.git (to revision 103d037) to /tmp/pip-install-jsvsku_v/openfold_a1fb3071bf26468684704ab751571b35
  Running command git clone --filter=blob:none --quiet https://github.com/aqlaboratory/openfold.git /tmp/pip-install-jsvsku_v/openfold_a1fb3071bf26468684704ab751571b35
  WARNING: Did not find branch or tag '103d037', assuming revision or ref.
  Running command git checkout -q 103d037
  Resolved https://github.com/aqlaboratory/openfold.git to commit 103d037
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: openfold
  Building wheel for openfold (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
[...]
FAILED: /tmp/pip-install-jsvsku_v/openfold_a1fb3071bf26468684704ab751571b35/build/temp.linux-x86_64-cpython-39/openfold/utils/kernel/csrc/softmax_cuda_kernel.o
      /usr/local/cuda-11.0/bin/nvcc  -I/tmp/pip-install-jsvsku_v/openfold_a1fb3071bf26468684704ab751571b35/openfold/utils/kernel/csrc/ -I/home/iwe34/anaconda3/envs/alphaflow/lib/python3.9/site-packages/torch/include -I/home/iwe34/anaconda3/envs/alphaflow/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/iwe34/anaconda3/envs/alphaflow/lib/python3.9/site-packages/torch/include/TH -I/home/iwe34/anaconda3/envs/alphaflow/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/iwe34/anaconda3/envs/alphaflow/include/python3.9 -c -c /tmp/pip-install-jsvsku_v/openfold_a1fb3071bf26468684704ab751571b35/openfold/utils/kernel/csrc/softmax_cuda_kernel.cu -o /tmp/pip-install-jsvsku_v/openfold_a1fb3071bf26468684704ab751571b35/build/temp.linux-x86_64-cpython-39/openfold/utils/kernel/csrc/softmax_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -std=c++14 -maxrregcount=50 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=attn_core_inplace_cuda -D_GLIBCXX_USE_CXX11_ABI=0
      nvcc fatal   : Unsupported gpu architecture 'compute_86'
[...]
```
[pip_openfold_error.txt](https://github.com/bjing2016/alphaflow/files/14430844/pip_openfold_error.txt)

**Comment by bjing2016** [comment]
It seems like you are compiling with CUDA 11.0. Although it should not be strictly necessary to use 11.6, 11.0 is probably too low. Could you upgrade your CUDA version to 11.4, the maximum supported by your NVIDIA driver? Note that the CUDA version given by nvidia-smi is not related to the version you actually have installed.

**Comment by Bloeci** [comment]
Oh cool. Thank you very much for the suggestion. That was the final trick i had to make to get everything run. 

For other people, I will post below everything I did to set up the environment correctly. I did everything with `conda` to have full control over the installation process (and I think it's easier). To speed up the `conda` solver, I recommend using the `libmamba` solver. The installation can be found [here] (https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community)

To get the correct cuda compiler for `cuda11.4` i've downloaded the runfile from [Nvidia](https://developer.nvidia.com/cuda-11-4-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=runfile_local) and install it **WITHOUT** the driver (during the installation you will be asked, simply remove the check mark). Then i add to following lines to my `.bashrc`
```bash
export CUDA_HOME=/usr/local/cuda-11.4
export CUDA_TOOLKIT_TARGET_DIR=/usr/local/cuda-11.4
export PATH="$PATH:/usr/local/cuda-11.4/bin"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-11.4/lib64
```

**My setup in this order**
```bash
conda create -n alphaflow python=3.9 numpy=1.21.6 pandas=1.5.3
conda install pytorch=2.0 pytorch-cuda torchvision torchaudio cudatoolkit=11.4 cuda-nvcc -c pytorch -c nvidia
conda install biopython=1.79 dm-tree modelcif ml-collections scipy absl-py einops -c conda-forge
conda install conda-forge::pytorch-lightning mdtraj wandb
pip install "fair-esm[esmfold]"
pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@103d037'
pip uninstall deepspeed
pip install deepspeed
```

**Note 1**: I chose the `pip` version for `"fair-esm[esmfold]"` because trying to install it with `conda` downgraded my `pytorch-cuda` version to `cpu`.
**Note 2**: Deintalling and installing `deepspeed` is a fix for the error `ModuleNotFoundError: No module named 'torch._six'` i encountered. Solution was shown [here](https://github.com/microsoft/DeepSpeed/issues/2845#issuecomment-1576127410).

**Comment by v-shaoningli** [comment]
@bjing2016 @Bloeci Proceed with this issue. Following the lateast version of openfold, these hyperparameters should be set at https://github.com/aqlaboratory/openfold/blob/main/openfold/config.py#L602 and https://github.com/aqlaboratory/openfold/blob/main/openfold/config.py#L576:
`"no_column_attention": False,
  "opm_first": False,
  "fuse_projection_weights": False,`
