### ISSUE TITLE
Multimer

### ISSUE THREAD

**Issue by MaciejMajew** [bjing2016/alphaflow#6]
Hi! Great work! 
Is multimer supported as in ESMFold?
I was trying to use a separation token ":" as in ESM but it doesn't seem to work.

**Comment by bjing2016** [comment]
We do not currently support ESM-style ":" tokens, but internally in ESMFold they are converted to linker sequences, which you can add manually. See https://github.com/facebookresearch/esm/blob/main/esm/esmfold/v1/misc.py#L18.
In the future we may add direct support for multimer inputs.

**Comment by MaciejMajew** [comment]
Thanks, I will try that solution for now.
