### ISSUE TITLE
scripts.unpack_mmcif.py reference to outdated betafold?

### ISSUE THREAD

**Issue by eduardoftoliveira** [bjing2016/alphaflow#7]
I tried to preprocess pdbs into NPZ files using "scripts/unpack_mmcif.py"
e.g.:
$ python -m scripts.unpack_mmcif.py --mmcif_dir ../testpdb/data_dir/ --outdir ../testpdb/outesmflow/

but it tries to load betafold:
"from betafold.data.data_pipeline import DataPipeline"

and fails:
"ModuleNotFoundError: No module named 'betafold'"

I tried to substitute "betafold.data.data_pipeline" for "alphaflow.data.data_pipeline" but I run into other issues that make me believe that "unpack_mmcif.py" is an outdated file.

Can you confirm this?

**Comment by bjing2016** [comment]
Thanks for the heads up, it's been updated!
